name: Lint
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-linter:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          miniforge-version: latest
      - name: pylint
        shell: bash -l {0}
        run: |
          pylint flatsurvey || true
      - name: black
        shell: bash -l {0}
        run: |
          black --check --diff flatsurvey
      - name: isort
        shell: bash -l {0}
        run: |
          isort --profile black --check --diff flatsurvey
