name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.55.0
      - name: pytest
        shell: pixi run bash -e {0}
        run: pixi run test
  survey:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.55.0
      - name: run survey
        shell: pixi run bash -e {0}
        run: |
          flatsurvey orbit-closure ngons --vertices 3 --limit 7 json --prefix survey
      - name: build cache database from previous run
        shell: pixi run bash -e {0}
        run: |
          # Creata single cache file from the runs.
          flatsurvey-maintenance join --outdir survey-results survey/**/*.json

          cat survey-results/orbit-closure.json
      - name: run survey from cache
        shell: pixi run bash -e {0}
        run: |
          # The survey succeeds with the cache enabled.
          flatsurvey orbit-closure ngons --vertices 3 --limit 7 local-cache --json survey-results/orbit-closure.json log --output -

          # The survey succeeds without running any computations.
          flatsurvey orbit-closure --cache-only ngons --vertices 3 --limit 7 local-cache --json survey-results/orbit-closure.json log --output -
