name: Test
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-flatsurvey:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.28.2
      - run: pixi run test
      - name: run survey
        shell: pixi run bash -e {0}
        run: |
          flatsurvey orbit-closure ngons --vertices 3 --limit 7 json
      - name: build cache database from previous run
        shell: pixi run bash -e {0}
        run: |
          # Shrink cache files by externalizing the referenced surfaces.
          mkdir -p pickles
          flatsurvey-maintenance externalize-pickles --pickles pickles/ *.json

          # Creata single cache file from the runs.
          flatsurvey-maintenance join *.json

          cat orbit-closure.json
      - name: run survey from cache
        shell: pixi run bash -e {0}
        run: |
          # The survey succeeds with the cache enabled.
          flatsurvey orbit-closure ngons --vertices 3 --limit 7 local-cache --json orbit-closure.json log

          # The survey succeeds without running any computations.
          flatsurvey orbit-closure --cache-only ngons --vertices 3 --limit 7 local-cache --json orbit-closure.json log
